version: "3.9"

services:
  shard1:
    image: postgres:16
    container_name: shard1
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
      POSTGRES_DB: shard1
    ports:
      - "5433:5432"
    volumes:
      - shard1_data:/var/lib/postgresql/data
      - ./sql/shard1:/docker-entrypoint-initdb.d

  shard2:
    image: postgres:16
    container_name: shard2
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
      POSTGRES_DB: shard2
    ports:
      - "5434:5432"
    volumes:
      - shard2_data:/var/lib/postgresql/data
      - ./sql/shard2:/docker-entrypoint-initdb.d

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: unless-stopped
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    ports:
      - "6432:6432"
    depends_on:
      - shard1
      - shard2

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  users-api:
    build: ./services/users-api
    container_name: users-api
    env_file:
      - ./services/users-api/.env
    ports:
      - "3000:3000"
    depends_on:
      - pgbouncer
      - shard1
      - shard2
      - redis

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - shard1
      - shard2

volumes:
  shard1_data:
  shard2_data:
